---

title: «Метамем»
timezone: UTC
description: Коллаборация

show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']

use_github_wiki: false
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false

  media: '/media'

  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - 404.md
    - README.md
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
