---

title: «Эта»
timezone: UTC
description: Коллаборация разработчиков цифровых и коммуникативных технологий

show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']

use_github_wiki: false
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false

prose:
  rooturl: 'https://indexmod.github.io/eta-space/'
  siteurl: 'https://indexmod.github.io/eta-space/'
  relativeLinks: 'https://prose.github.io/starter/links.jsonp'
  media: '/media'

  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - 404.md
    - README.md
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
