title: Metamem
description: Metamem is a theme for GitHub Pages
google_analytics:
theme: jekyll-theme-minimal
show_sidebar: false
show_downloads: false
show_title: false
show_description: false
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false
